from __future__ import annotations

from .action_manager import ActionManager
from .actions import (
    AddMarker,
    AddUnit,
    Attack,
    ClearHexdemoCombatExtension,
    ClearTitleCombatExtension,
    ClearUnitRetreatObligation,
    DeleteUnit,
    MoveMarker,
    MoveUnit,
    NextPhase,
    PatchUnitAttributes,
    RemoveMarker,
    ResolvePassMovementInterrupt,
    SetTurnState,
    SpendAction,
    WriteHexengineMovementArc,
)
from .game_state import (
    BoardEdgeFeature,
    BoardLinearFeature,
    BoardState,
    GameState,
    LocationState,
    TurnState,
    UnitState,
    UnsetTerrainDefaults,
)
from .logic import (
    DEFAULT_MOVEMENT_BUDGET,
    adjacent_enemy_zoc_hexes,
    adjacent_friendly_zoc_hexes,
    compute_reachable_hexes,
    compute_retreat_destination_hexes,
    compute_valid_moves,
    get_blocking_hexes,
    has_line_of_sight,
    is_valid_move,
    los_visible_hexes_in_cone,
    retreat_impassable_enemy_zoc_hexes,
    shortest_move_path,
)
from .map_feature_queries import (
    board_edge_features_along_hex_line,
    edge_keys_along_hex_line,
    edge_line_of_sight_blocks_hex_line,
    edge_movement_extra_for_neighbor_step,
    edges_block_los_predicate,
    linear_features_on_neighbor_step,
    min_linear_movement_cost_for_tags,
)
from .marker_placement import (
    MarkerPlacementRule,
    default_marker_destination_allowed,
    marker_destination_hexes_for_preview,
)
from .snapshot import (
    SNAPSHOT_FORMAT_VERSION,
    game_state_from_wire_dict,
    game_state_to_wire_dict,
)

__all__ = [
    "SNAPSHOT_FORMAT_VERSION",
    "game_state_from_wire_dict",
    "game_state_to_wire_dict",
    "GameState",
    "BoardState",
    "BoardEdgeFeature",
    "BoardLinearFeature",
    "UnitState",
    "LocationState",
    "UnsetTerrainDefaults",
    "TurnState",
    "ActionManager",
    "MoveUnit",
    "Attack",
    "ClearHexdemoCombatExtension",
    "ClearTitleCombatExtension",
    "ClearUnitRetreatObligation",
    "MoveMarker",
    "AddMarker",
    "RemoveMarker",
    "ResolvePassMovementInterrupt",
    "DeleteUnit",
    "AddUnit",
    "SpendAction",
    "NextPhase",
    "PatchUnitAttributes",
    "SetTurnState",
    "WriteHexengineMovementArc",
    "DEFAULT_MOVEMENT_BUDGET",
    "adjacent_enemy_zoc_hexes",
    "adjacent_friendly_zoc_hexes",
    "compute_reachable_hexes",
    "compute_valid_moves",
    "get_blocking_hexes",
    "has_line_of_sight",
    "is_valid_move",
    "compute_retreat_destination_hexes",
    "los_visible_hexes_in_cone",
    "retreat_impassable_enemy_zoc_hexes",
    "shortest_move_path",
    "MarkerPlacementRule",
    "default_marker_destination_allowed",
    "marker_destination_hexes_for_preview",
    "edge_keys_along_hex_line",
    "board_edge_features_along_hex_line",
    "linear_features_on_neighbor_step",
    "min_linear_movement_cost_for_tags",
    "edge_movement_extra_for_neighbor_step",
    "edge_line_of_sight_blocks_hex_line",
    "edges_block_los_predicate",
]
